language: node_js

node_js:
    - "9"

sudo: required

install:
  - npm install

test:
  - npm run test

jobs:
  include:
    - stage: npm release
      node_js: "9"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        auth_token: $NPM_AUTH_TOKEN
        on: deploy-npm-release
